# Root directory
root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"     # Where built binary goes
  cmd = ""             # Empty -> Air auto-detects main.go and builds it
  delay = 1000         # 1s debounce on file changes
  exclude_dir = ["tmp", "vendor"] # Ignore these dirs
  exclude_regex = ["_test.go"]    # Ignore test files
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "2s"
  log = "air.log"
  #poll = true
  #poll_interval = 10000


[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
